[package]
name = "ceph_dead_disk"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
blkid = "*"
block-utils = "*"
ceph-rust = "*"
clap = "*"
goji = {git = "https://github.com/cholcombe973/goji"}
log = "*"
rusqlite = "*"
simplelog = "*"
time = "*"
