[package]
name = "ceph_dead_disk"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
blkid = "*"
block-utils = {path = "/home/chris/repos/block-utils"}
ceph-rust = {path = "/home/chris/repos/ceph-rust"}
clap = "*"
dmi = {path = "/home/chris/repos/dmi"}
goji = {git = "https://github.com/cholcombe973/goji"}
json = "*"
libc = "*"
log = "*"
rusqlite = "*"
serde_json = "*"
simplelog = "*"
time = "*"
uuid = "*"
