[package]
name = "ceph_dead_disk"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
# blkid = "*"
block-utils = {git = "https://github.com/cholcombe973/block-utils"}
ceph-rust = {git = "https://github.com/cholcombe973/ceph-rust"}
ceph-safe-disk = {git = "https://github.com/cholcombe973/ceph_safe_disk"}
clap = "*"
dmi = {git = "https://github.com/cholcombe973/dmi"}
fstab = "*"
goji = {git = "https://github.com/cholcombe973/goji"}
json = "*"
libatasmart = "*"
libc = "*"
log = "*"
mktemp = "*"
# protobuf = "*"
rusqlite = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
simplelog = "*"
time = "*"
uname = "*"
uuid = "*"
