[package]
name = "parallel-deploy"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
api = { path = "../api", version = "*"}
clap = "*"
helpers = { path="../helpers", version="*"}
log = "*"
protobuf = "*"
rayon = "*"
simplelog = "*"
zmq = "*"
